version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - run:
          name: Store Service Account
          command: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run: |
             gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
             gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
             gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
             gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}

#version: 2
# jobs:
#   build:
#     docker:
#       - image: golang:1.10-alpine
#
#     working_directory: $CIRCLE_WORKING_DIRECTORY
#
#     steps:
#       - checkout
#       - run: apk add -U git
#       - run: go get -v -t -d ./...
#       - run: go run main.go
