version: 2
jobs:
  build:
    docker:
      - image: golang:1.10-alpine

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go run main.go
